%% Call below command to convert .mmd to .png
%%  Adjust -w or -H if necessary
%% mmdc -p puppeteer-config.json -i golang_pkg_import_graph.mmd -o golang_pkg_import_graph.mmd.png -w 960 -H 540

%%```mermaid

graph BT

Title[<u> pkg Import Graph</u>]
Title-->pkggraph
style Title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0;

pkggraphsample1["(pkg)graphsample1"] --> pkggraph["(pkg)graph"]
pkggraphsample2["(pkg)graphsample2"] --> pkggraph
pkggraphsample3["(pkg)graphsample3"] --> pkggraph

pkglevelgraph["(pkg)levelgraph"] --> pkggraph

pkgbfs["(pkg)bfs"] --> pkggraph
pkgbfs --> pkggraphsample1
pkgbfs --> pkglevelgraph

bfs_main("(bin)bfs_main") --> pkgbfs
bfs_main --> pkggraphsample1
bfs_main --> pkggraph

pkgdfs["(pkg)dfs"] --> pkggraph
pkgdfs --> pkggraphsample2
pkgdfs --> pkggraphsample3

pkgflownetwork["(pkg)flownetwork"] --> pkggraph

pkgmaxflow["(pkg)maxflow"] --> pkgflownetwork
pkgmaxflow --> pkgdfs
pkgmaxflow --> pkgbfs
pkgmaxflow --> pkggraph
pkgmaxflow --> pkglevelgraph


maxflow_main("(bin)maxflow_main") --> pkgflownetwork
maxflow_main("(bin)maxflow_main") --> pkgmaxflow

%%```
